"""Auto FIR (First Information Report) draft generation for Indian police filing."""

from datetime import datetime
from typing import Optional


def generate_fir_draft(
    incident_id: str,
    complainant_name: str,
    complainant_mobile: str,
    incident_type: str,
    latitude: float,
    longitude: float,
    description: str = "",
    evidence_hashes: Optional[list[str]] = None,
    created_at: Optional[datetime] = None,
) -> dict:
    """Generate a structured FIR draft from incident data.

    Returns a dictionary containing all fields needed for a First Information Report
    as per Indian Criminal Procedure Code (CrPC) Section 154.
    """
    timestamp = created_at or datetime.utcnow()
    fir_number = f"FIR/{timestamp.strftime('%Y%m%d')}/{incident_id[:8].upper()}"

    # Map incident types to IPC sections
    ipc_sections = {
        "sos": "Section 354 IPC (Assault on woman), Section 506 IPC (Criminal intimidation)",
        "stalking": "Section 354D IPC (Stalking)",
        "harassment": "Section 354A IPC (Sexual harassment), Section 509 IPC (Word/gesture to insult modesty)",
        "cyber_fraud": "Section 66C IT Act (Identity theft), Section 66D IT Act (Cheating by personation)",
        "blackmail": "Section 383 IPC (Extortion), Section 384 IPC (Punishment for extortion)",
        "deepfake": "Section 66E IT Act (Privacy violation), Section 500 IPC (Defamation)",
        "phishing": "Section 66C IT Act (Identity theft), Section 420 IPC (Cheating)",
    }

    applicable_sections = ipc_sections.get(
        incident_type,
        "Section 354 IPC (Assault on woman with intent to outrage modesty)",
    )

    fir_draft = {
        "fir_number": fir_number,
        "police_station": "Cyber Crime Branch, Ahmedabad City",
        "district": "Ahmedabad",
        "state": "Gujarat",
        "date_of_report": timestamp.strftime("%d/%m/%Y %H:%M IST"),
        "complainant": {
            "name": complainant_name,
            "contact": complainant_mobile,
        },
        "incident_details": {
            "type": incident_type,
            "date_time": timestamp.strftime("%d/%m/%Y %H:%M IST"),
            "location": f"Lat: {latitude}, Lng: {longitude}",
            "description": description or f"Emergency {incident_type} incident reported via CyberShield app.",
        },
        "applicable_sections": applicable_sections,
        "evidence": {
            "digital_evidence_count": len(evidence_hashes) if evidence_hashes else 0,
            "evidence_hashes": evidence_hashes or [],
            "evidence_source": "CyberShield Evidence Vault (SHA-256 verified, AES-256 encrypted)",
        },
        "investigation_officer": "To be assigned",
        "status": "Draft — pending review by Station House Officer",
        "generated_by": "CyberShield Auto-FIR System v1.0",
        "disclaimer": (
            "This is an auto-generated draft FIR for preliminary filing. "
            "Final FIR must be reviewed and signed by the Station House Officer."
        ),
    }

    return fir_draft


def fir_to_text(fir: dict) -> str:
    """Convert a FIR draft dictionary to a printable text format."""
    lines = [
        "=" * 60,
        "FIRST INFORMATION REPORT (FIR) — DRAFT",
        "=" * 60,
        f"FIR Number      : {fir['fir_number']}",
        f"Police Station  : {fir['police_station']}",
        f"District        : {fir['district']}, {fir['state']}",
        f"Date of Report  : {fir['date_of_report']}",
        "-" * 60,
        "COMPLAINANT DETAILS",
        f"  Name    : {fir['complainant']['name']}",
        f"  Contact : {fir['complainant']['contact']}",
        "-" * 60,
        "INCIDENT DETAILS",
        f"  Type        : {fir['incident_details']['type']}",
        f"  Date & Time : {fir['incident_details']['date_time']}",
        f"  Location    : {fir['incident_details']['location']}",
        f"  Description : {fir['incident_details']['description']}",
        "-" * 60,
        f"APPLICABLE SECTIONS: {fir['applicable_sections']}",
        "-" * 60,
        "DIGITAL EVIDENCE",
        f"  Evidence Count  : {fir['evidence']['digital_evidence_count']}",
        f"  Source          : {fir['evidence']['evidence_source']}",
        "-" * 60,
        f"IO Assigned     : {fir['investigation_officer']}",
        f"Status          : {fir['status']}",
        f"Generated By    : {fir['generated_by']}",
        "",
        fir["disclaimer"],
        "=" * 60,
    ]
    return "\n".join(lines)
